########################### XACT'S ENVIRONMENT
# Here are my 2 Docker Hosts:
# - Home Server (nuc) - Intel NUC with Unraid OS 7.0.1
# - Web Server (oci) - Oracle Cloud Instance with Ubuntu 24.04

########################### THIS COMPOSE FILE
# - Web Server (oci) - Oracle Cloud Instance with Ubuntu 24.04
# - Prefix/suffix "oci" refers to the above host
# - Docker version 24.0.7, build afdd53b
# - Docker Compose version v2.33.1

###############################################################
# Networks
###############################################################
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

###############################################################
# Docker Secrets
# Owner (default): root:root
# Recommend Set Owner to match container user Example: UID=1100, GID=1100
# Permissions of files & directory on host to: 0400 (-r--)
###############################################################
secrets:
  ## Cloudflare / Traefik
  default_username:
    file: ${DOCKERDIR}/secrets/default_username
  cf_email:
    file: ${DOCKERDIR}/secrets/cf_email
  traefik_forward_auth:
    file: $DOCKERDIR/secrets/traefik_forward_auth
  # cf_api_key:
  #   file: ${DOCKERDIR}/secrets/cf_api_key
  cf_dns_api_token:
    file: ${DOCKERDIR}/secrets/cf_dns_api_token
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  ## Databases
  postgres_default_password:
    file: $DOCKERDIR/secrets/postgres_default_password
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password
  ## Authentik
  authentik_postgresql_db:
    file: ${DOCKERDIR}/secrets/authentik_postgresql_db
  authentik_postgresql_user:
    file: ${DOCKERDIR}/secrets/authentik_postgresql_user
  authentik_postgresql_password:
    file: ${DOCKERDIR}/secrets/authentik_postgresql_password
  authentik_secret_key:
    file: ${DOCKERDIR}/secrets/authentik_secret_key
  gmail_smtp_username:
    file: ${DOCKERDIR}/secrets/gmail_smtp_username
  gmail_smtp_password:
    file: ${DOCKERDIR}/secrets/gmail_smtp_password
  ## Rustdesk
  rustdesk_private_key:
    file: ${DOCKERDIR}/secrets/rustdesk_private_key
  rustdesk_public_key:
    file: ${DOCKERDIR}/secrets/rustdesk_public_key
  ## Headplane
  headplane_cookie_secret:
    file: ${DOCKERDIR}/secrets/headplane_cookie_secret
  ## Komodo
  komodo_db_username:
    file: ${DOCKERDIR}/secrets/komodo_db_username
  komodo_db_password:
    file: ${DOCKERDIR}/secrets/komodo_db_password
  komodo_passkey:
    file: ${DOCKERDIR}/secrets/komodo_passkey

###############################################################
# Include
# Merge all of the below compose files into one large compose at run time
# Thanks to Anand (SmartHomeBeginner), this is clean!
###############################################################
include:

  # CORE
  - compose/traefik.yml
  - compose/authentik.yml
  - compose/komodo.yml
  # SECURITY
  # - compose/crowdsec.yml
  # - compose/traefik-bouncer.yml
  # FRONTEND
  # - compose/phpmyadmin.yml
  - compose/whoami.yml
  # https://aaronjbecker.com/posts/self-hosted-analytics-umami-docker-compose-traefik/
  - compose/umami.yml
  - compose/vaultwarden.yml
  # GAME SERVERS
  - compose/minecraft.yml
  # DOWNLOADERS
  # - compose/jdownloader.yml
  # MONITORING
  - compose/uptime-kuma.yml
  - compose/dozzle.yml
  # ADMIN
  - compose/rundeck-server.yml
  
  # UTILITIES
  - compose/it-tools.yml
  # FILE MANAGEMENT
  - compose/vscode.yml
  # NETWORK
  # headscale setup:
  # https://timharek.no/blog/i-switched-from-wireguard-to-headscale/
  # https://blog.flaskforge.com/Docker/headscale
  - compose/headscale.yml